version: '3.8'

services:
  database:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical_forum
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - forum_network

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/medical_forum
    depends_on:
      - database
    networks:
      - forum_network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/medical_forum
    depends_on:
      - database
    networks:
      - forum_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
      - auth-service
    networks:
      - forum_network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - auth-service
    networks:
      - forum_network

volumes:
  db_data:

networks:
  forum_network:
