version: '3.8'

services:
  database:
    build: ./database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=medical_forum
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://user:password@database/medical_forum

  auth-service:
    build: ./auth-service
    ports:
      - "8001:8000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://user:password@database/medical_forum

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data: