version: '3.8'

services:
  database:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical_forum
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - forum_network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/medical_forum
    depends_on:
      - database
    networks:
      - forum_network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/medical_forum
    depends_on:
      - database
    networks:
      - forum_network

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
      - auth-service
    volumes:
      - type: bind
        source: ./frontend
        target: /usr/share/nginx/html
      - type: bind
        source: ./frontend/conf.d
        target: /etc/nginx/conf.d
    networks:
      - forum_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
      - auth-service
    networks:
      - forum_network

volumes:
  db_data:

networks:
  forum_network:
