FROM nginx:latest

# Копируем файл конфигурации Nginx
COPY ./nginx.conf /etc/nginx/nginx.conf

# Копируем статические файлы фронтенда (если необходимо)
#COPY ../frontend/static /usr/share/nginx/html/static

# Открываем порт для доступа
EXPOSE 80
